### ISSUE TITLE
Image Build only uses trunk

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMXAnalysis/ldmx-sw#1008]
**Describe the bug**
The [build_production_image.yml](https://github.com/LDMX-Software/ldmx-sw/blob/trunk/.github/workflows/build_production_image.yml) workflow was designed to allow the user to input a branch of ldmx-sw to build into the image. The workflow pulls down the branch and then builds the image, but the docker/build-push-action pulls down its own copy of ldmx-sw in order to build the image. Its own copy is always the `GITHUB_REF` that triggered the action.

**To Reproduce**
1. [Launch a workflow](https://github.com/LDMX-Software/ldmx-sw/actions/workflows/build_production_image.yml) on a non-trunk branch.
2. Wait 15 minutes
3. Download the new production image and see that it is still `trunk`.

**Desired behavior**
We'd like the manually-launched workflow to actually do what its told.
This can be achieved by providing the build-push-action with the branch that we want it to use as its context.

```yaml
    -
      name: Build the Image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        tags: ${{ steps.generate_tag.outputs.tags }}
        push: true
        context: github.com/LDMX-Software/ldmx-sw/tree/${{ github.event.inputs.branch }}
```
