### ISSUE TITLE
using `clang-tidy` for coding rules and linting

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMXAnalysis/ldmx-sw#1709]
`clang-tidy` can go a bit further than `clang-format`, enforcing many of our [Coding Rules](https://ldmx-software.github.io/developing/coding-rules.html) (e.g. naming conventions) as well as provide some helpful preventative measures to avoid common issues that can be found via static analysis.

## Notes
- CMake generates a "compile command database" for us, which is required by `clang-tidy` to function. Use the `-p` argument to provide the build directory.
- Like `clang-format`, we need to provide the files to tidy. Probably could do something similar to `just format-cpp` where we write a file listing using `find`
- Looks in current directory's `.clang-tidy` file for configuration.
- Provide `--fix` argument to apply the fix (if possible)
- `--warnings-as-errors` argument to fail on CI?

## Config
Scaffolding up the YAML to go into a `.clang-tidy` file
```yaml
# comma-separated list of globs to enable or disable (`-` prefix)
# this one disables all and then enables readability-identifier-naming
Checks: "-*,readability-identifier-naming"
# options to checks
CheckOptions:
  readability-identifier-naming.FunctionCase: camelBack
  readability-identifier-naming.NamespaceCase: lower_case
  readability-identifier-naming.ClassCase: CamelCase
  readability-identifier-naming.StructCase: CamelCase
  readability-identifier-naming.VariableCase: lower_case
  readability-identifier-naming.GlobalConstantCase: UPPER_CASE
  readability-identifier-naming.MemberCase: lower_case
  readability-identifier-naming.MemberSuffix: "_"
  readability-identifier-naming.ConstantMemberCase: UPPER_CASE
```
